### ISSUE TITLE
Make TypeForm screener/app

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/getcalfresh.org#1]
- [x] Forward getfoodstamps.org and getcalfresh.com > getcalfresh.org
- [x] Review AR wording
- [x] Redirect to doc upload at end
- [x] Improve terms (explain what's going on, give alternative)
- [x] Make entires > Google Spreadsheet
- [x] Typeform > Front issue
- [x] Get typeform on GetCalFresh.org
- [x] Make sure it works on mobile
- [x] Get unique ID > send to doc upload
- [x] Add back calling so we can do user research that way (but text OR email is required?)
- [x] Review
  - [x] @daguar
  - [x] @alanjosephwilliams 

Outline
- Screen
  - HH
  - Citizen
  - Income
  - Student
  - SSI
- Apply
  - Contact info
  - SSN
  - AR
  - Sig

**Comment by daguar** [comment]
How are we imagining the flow from the form to the doc uploader? Specifically, will any data be passed by params that we can use to identify the user when saving docs in the database?

**Comment by lippytak** [comment]
Good question. Looks like we can pass any data from the Typeform via a GET
param, like this:
[image: Inline image 1]

It would be cleaner to have a unique ID but doesn't look like Typeform
generates one that we can use here. If we could include a unique ID from
Google/Bing in the URL that would work...I'll look into it more
<https://support.google.com/adwords/answer/2549100?hl=en>.

**Comment by lippytak** [comment]
Actually looks like this will be pretty easy: https://support.google.com/adwords/answer/2375447?hl=en

So assume you have a GET param with a unique ID.

**Comment by lippytak** [comment]
Ready for review @daguar + @alanjosephwilliams

**Comment by daguar** [comment]
I'm checking it out; FYI the image in the above comment didn't seem to get inserted (I've seen a few of these on your end so check preview the next time you drag and drop to see if something's up with that flow.)

**Comment by daguar** [comment]
Re legal resident question:

![screen shot 2015-05-12 at 8 05 44 am](https://cloud.githubusercontent.com/assets/994938/7590505/b806e1d0-f87d-11e4-8ecd-82e775d3cb91.png)

My understanding from the training was that in general you need to be a PERMANENT legal resident to be eligible. Is that right?

**Comment by daguar** [comment]
"How can we send you updates?" screen — change "we'll check-in" to "we'll check in" for grammar pain.

**Comment by daguar** [comment]
Can we ask for phone number earlier? Putting it below the "how do we contact you" screen implies that maybe we ONLY use it for contact when in reality it's like the most important thing. I'd put it towards the top.

**Comment by daguar** [comment]
At "does this look right?" screen, can we say "# of people in your household: 2" rather than "household size"? Just a tiny usability improvement.

**Comment by daguar** [comment]
For AR screen, can we add a middle paragraph that's something like "we recommend having an AR so we can help make sure your application is processed correctly" or other?

Feels like giving some actual _reason_ why we ask for this is enough context for lots of people to get in, but we don't give one now.

**Comment by daguar** [comment]
In legal stuff, missing space between sentences here:

>  - I read or had read to me and I understand and agree to the Rights and Responsibilities (www.bit.ly/calfresh-rights) for the CalFresh Program.I read, or had read to me, the CalFresh Program Rules and Penalties (http://bit.ly/calfresh-rules).

**Comment by daguar** [comment]
For legal stuff, we say "I accept" but the error says "You must agree" — should we say agree, or accept?

**Comment by daguar** [comment]
On legal stuff, can the error message be friendlier? 

So instead of "You must agree to the Terms & Conditions"

something like "You have to agree to these terms submit a CalFresh application on this site"

**Comment by daguar** [comment]
@daguar review is complete.

**Comment by lippytak** [comment]
@daguar thanks! Made all changes except didn't add more text to AR. Instead I clarified the value prop in the first sentence and bolded it: "...make sure your application is being processed properly"

**Comment by lippytak** [comment]
Remaining small issues separated out
