### ISSUE TITLE
Template SMS/email messages

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/getcalfresh.org#11]
- Confirmation = what's next
- 10 day FU = did you interview?
- 20 day FU = did you verify?
- 30 day FU = did you get approved?
- [x] Draft via Front response templates
- [ ] Review
- [x] Practice flow/timing

**Comment by lippytak** [comment]
@daguar and @alanjosephwilliams Would love if you could review the canned responses in Front and give feedback here.

**Comment by lippytak** [comment]
@alanjosephwilliams  confirmation, 10 day, 20 day, 30 day notes all drafted. Ready for review!

**Comment by alanjosephwilliams** [comment]
Review:
- [x] 10 day
- [x] 20 day
- [x] 30 day
- [x] confirmation

Small changes, mostly to formatting and slight word choices. Great job.
