### ISSUE TITLE
Write an awesome confirmation page

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/getcalfresh.org#14]
Outline what to expect and what to do next. We only need this right now if we don't do #3 for v1.

**Comment by daguar** [comment]
On current confirmation page, which looks like this

![screen shot 2015-05-12 at 8 19 27 am](https://cloud.githubusercontent.com/assets/994938/7590916/a16dc284-f87f-11e4-8dfe-d82c70f926ea.png)

I'd suggest we have a clear call-to-action to contact us with any questions, since now we're asking for documents that are kinda sensitive (yes, I know they've already given their SSN, but still.)

**Comment by lippytak** [comment]
See if we can make the button open an email client

**Comment by alanjosephwilliams** [comment]
sadly, mailto links won't work with the Typeform button, which
automatically appends "http://" to any content pasted into the field. I've
removed the button for now.

On Tue, May 12, 2015 at 12:14 PM, Jake Solomon <notifications@github.com>
wrote:

> Assigned #14 <https://github.com/codeforamerica/getcalfresh.org/issues/14>
> to @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/getcalfresh.org/issues/14#event-303141199>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by alanjosephwilliams** [comment]
Current confirmation page. Not quite awesome, but pretty much ready to ship.

- added notice that they should receive a confirmation message
- added graphic illustrating the steps outstanding
- added sentence to set expectations about a phone interview.

[image: Inline image 1]

On Tue, May 12, 2015 at 10:49 PM, Alan Williams <
alanjosephwilliams@gmail.com> wrote:

> sadly, mailto links won't work with the Typeform button, which
> automatically appends "http://" to any content pasted into the field.
> I've removed the button for now.
>
> On Tue, May 12, 2015 at 12:14 PM, Jake Solomon <notifications@github.com>
> wrote:
>
>> Assigned #14
>> <https://github.com/codeforamerica/getcalfresh.org/issues/14> to
>> @alanjosephwilliams <https://github.com/alanjosephwilliams>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/codeforamerica/getcalfresh.org/issues/14#event-303141199>
>> .
>>
>
>
>
> --
> t:  @alanjosephwilli
> p: 817 713 6264
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
@alanjosephwilliams — Can you repost the image of the confirmation page into the GitHub interface? It's showing up as "[image: Inline image 1]" to me. Thanks!

**Comment by alanjosephwilliams** [comment]
@daguar here ya go
![getcalfresh_confirmation_v3](https://cloud.githubusercontent.com/assets/2983464/7616318/58b7338e-f958-11e4-92b7-380ccc715895.png)
