### ISSUE TITLE
Enable SSL on the domain

### ISSUE THREAD

**Issue by daguar** [codeforamerica/getcalfresh.org#18]

**Comment by lippytak** [comment]
@daguar would you actually mind digging into this a bit more and making a recommendation?

See: https://github.com/isaacs/github/issues/156 and https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it. From the second source:  "You can't use a custom domain name with a fully secured HTTPS connection"

Should we move to heroku? Or something else?

**Comment by daguar** [comment]
Will do

**Comment by lippytak** [comment]
@daguar can you set this up on heroku?

**Comment by daguar** [comment]
BOOM, thx to @migurski for teh hlep
