### ISSUE TITLE
Test Typeform on Android

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/getcalfresh.org#22]

**Comment by daguar** [comment]
I played around a little bit on @lippytak's cheapo Android he bought and it feels great! A little bit slow to load initially is all, but pretty good experience.

**Comment by daguar** [comment]
I did the whole flow on the Android and it was great, so I am marking this as done since I think the core of this is just a smoke test that it works.

**Comment by alanjosephwilliams** [comment]
I'm testing it on the android I have at home now, and we are looking good
:+1:

On Tue, May 12, 2015 at 6:56 PM, Dave Guarino <notifications@github.com>
wrote:

> Closed #22 <https://github.com/codeforamerica/getcalfresh.org/issues/22>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/getcalfresh.org/issues/22#event-303416152>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
:+1:
