### ISSUE TITLE
% completed isn't totally correct

### ISSUE THREAD

**Issue by daguar** [codeforamerica/getcalfresh.org#27]
Seems like the first few questions you do, it thinks the survey is only 4 questions (so, after answering 2, it says 50% completed.)

Anyone know what's up with that?

**Comment by lippytak** [comment]
That's lame. Looks like it only shows progress up to next branching point. Bug. I'd rather be noncommittal than a liar  so removed for now.

**Comment by daguar** [comment]
Can you have the %age on a specific branch? ie, could we do it on the second (bigger) branch only?

**Comment by lippytak** [comment]
Unfortunately no. On or off. Also we have a few different branch points so it would keep getting weird.

**Comment by daguar** [comment]
Darn, okay. Well :+1: to your decision, but let's think in the future how we might give them some context at the beginning of rough timeframe, like "this application will take about 10-15 minutes."
