### ISSUE TITLE
Say "application" not "official application"

### ISSUE THREAD

**Issue by daguar** [codeforamerica/getcalfresh.org#31]
Tiny but it'd make me feel better. It's after the "good news" thing.

**Comment by lippytak** [comment]
If you think we're missing important info that would help the user make a good decision (not just make us feel safer) then I'd propose we put it in the summary of 'legal.' I'm ambivalent that saying "not official" does users any good.

**Comment by daguar** [comment]
> I'm ambivalent that saying "not official" does users any good.

Totally fair, but I guess I'm not saying we say "not official" — just saying we say "application" instead of "official application." Removing official seems to have little to no user downside when I look at it. But happy to discuss IRL or on Slack.

**Comment by lippytak** [comment]
Agreed/done. Had forgotten we said that. Close this for now?
