### ISSUE TITLE
Make Jake's LinkedIn profile an actual link

### ISSUE THREAD

**Issue by daguar** [codeforamerica/getcalfresh.org#32]
needs the http:// before it

**Comment by alanjosephwilliams** [comment]
That won't make it an actual link, but I have added it so the user can copy
and paste more easily.

On Tue, May 12, 2015 at 6:38 PM, Dave Guarino <notifications@github.com>
wrote:

> needs the http:// before it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/getcalfresh.org/issues/32>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
