### ISSUE TITLE
Final "email documents" button link is broken

### ISSUE THREAD

**Issue by daguar** [codeforamerica/getcalfresh.org#33]
The link shows up as:

`mailto/?body=http://application/confirmation&subject=Congratulations!%20You%20applied%20for%20CalFresh`

**Comment by daguar** [comment]
Moving to current sprint since I think it needs to work prior to shipping

**Comment by alanjosephwilliams** [comment]
you caught me trying to make a mailto link work. sadly, they don't, as
typeform appends an http:// to anything pasted in the the button link form
field. the button has been removed.

On Tue, May 12, 2015 at 6:44 PM, Dave Guarino <notifications@github.com>
wrote:

> Moving to current sprint since I think it needs to work prior to shipping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/getcalfresh.org/issues/33#issuecomment-101479982>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
